### PR TITLE
Add elastio_inspector python

### PR DESCRIPTION
**Pull request by vchokshi**
# PR Description

Elastio Inspector reviews all regional artifacts for Elastio. It has a -d flag that allows for destruction of resources.

# Testing
Run tox.

### CODE REVIEW

**Review by anelson — APPROVED** [review]
LGTM, but I think the `README` should call out the `-d` flag as a way to delete all resources.  I hope that won't be useful once we reach our Prod Ready milestone and upgrades are working, but it's been useful up to this point so may as well document it.

**Comment by vchokshi** [comment]
Thanks @anelson this one is ready to go.

**Comment by mvovchuk** [comment]
this is the clean up script - we would not want to merge it at the moment, will reiterate on it eventually

**Comment by vchokshi** [comment]
Yes, we dont need this anymore, we're using `aws-nuke`. Thank you.

**Pull request closed without merging**
